### ISSUE TITLE
在windows10系统下make出现filesystem: No such file or directory

### ISSUE THREAD

**Issue by 124asd** [nextgal/pfs_upk#4]
我在windows10系统先cmake后 再运行make 出现了如图所示的错误 请问要怎么解决
![error](https://user-images.githubusercontent.com/67571290/178090910-371af77e-c6cd-449a-9859-463f4e83b6fa.png)

**Comment by ryank231231** [comment]
请检查你的 C++ 编译器是否支持 C++ 17 标准。

**Comment by asdetycv1zzc** [comment]
在顶层cmake中加入：
set(CMAKE_CXX_STANDARD 17)

**Comment by ryank231231** [comment]
https://github.com/nextgal/pfs_upk/blob/b0233cd0e3af64bddd4b7168b49f91376dfc8d7c/CMakeLists.txt#L4

本项目的 CMake 文件中已经声明了 C++ 标准。（

**Comment by 124asd** [comment]
> 
非常抱歉很晚回复 昨天有事没继续执行 不过我后面改用的gcc/g++均是8.1版本  查询g++8.1版本是已经支持C++17标准的 然后
![(M0G1K$C A(9KOA`AO9}12R](https://user-images.githubusercontent.com/67571290/178175646-e5b0045d-1d5f-4a68-8f23-14b1b1a2c00f.png)

**Comment by asdetycv1zzc** [comment]
filesystem在gcc上似乎没有被完整实现？
可以尝试msvc编译

**Comment by 124asd** [comment]
> filesystem在gcc上似乎没有被完整实现？ 可以尝试msvc编译

非常谢谢您的回复 我估计我那边是不能完全实现了 就换了另一种解决方案 感谢您们的帮助 抱歉打扰您们了
