### ISSUE TITLE
[Question]  Do you know if there is any way to create a pfs patch?

### ISSUE THREAD

**Issue by Saipan0** [nextgal/pfs_upk#9]
First of all thank you for your tool. ;)
I wanted to ask if you knew if with the Artemis engine, there was a way to create a patch? Like how it happens with kirikiri and others..
i tried patch.pfs , script.pfs but nothing, none of them work.
Thanks you

**Comment by ryank231231** [comment]
`root.pfs.00x` / `<programName>.pfs.00x`

**Comment by Saipan0** [comment]
> `root.pfs.00x` / `<programName>.pfs.00x`

Thanks for replying. Resolved
